---
deployment:
  tasks:
    - cd /home/bibnumca/react_repo && npm install
    - cd /home/bibnumca/react_repo && npm run build
    - cp -r /home/bibnumca/react_repo/dist/. /home/bibnumca/public_html/donalgros-gestion.com/